[package]
name = "better-alignment"
version = "0.1.0"
authors = ["c0deb0t <daniel.liu02@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
panic = "abort"
debug-assertions = false

[profile.bench]
codegen-units = 1
debug-assertions = false

[dependencies]

[dev-dependencies]
rand = "^0.7"
